<a href="https://colab.research.google.com/github/thallamsaithrishool12-alt/Applicatios_of_Data_Mining/blob/main/1)Data_Preprocessing_and_Feature_Scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [8]:
data=pd.read_csv("/content/mental_health_dataset.csv")
data.head()

   User_ID  Age      Gender  ... Sleep_Hours Work_Hours Physical_Activity_Hours
0        1   52        Male  ...         9.5         26                       6
1        2   39  Non-binary  ...         4.3         47                       7
2        3   44        Male  ...         9.2         49                       1
3        4   24      Female  ...         6.1         63                       4
4        5   42      Female  ...         7.1         38                       8

[5 rows x 12 columns]

In [9]:
print("missing values before imputation:")
print(data.isnull().sum())

missing values before imputation:
User_ID                    0
Age                        0
Gender                     0
Occupation                 0
Country                    0
Mental_Health_Condition    0
Severity                   0
Consultation_History       0
Stress_Level               0
Sleep_Hours                0
Work_Hours                 0
Physical_Activity_Hours    0
dtype: int64

In [12]:
data['Work_Hours'].fillna(data['Work_Hours'].mean(),inplace=True)

/tmp/ipykernel_838/696488699.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Work_Hours'].fillna(data['Work_Hours'].mean(),inplace=True)

In [16]:
data['Age'].fillna(data['Age'].mean(),inplace=True)
data['Work_Hours'].fillna(data['Work_Hours'].mode()[0],inplace=True)

/tmp/ipykernel_838/2908008600.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Work_Hours'].fillna(data['Work_Hours'].mode()[0],inplace=True)

In [17]:
print("missing values after imputation:")
print(data.isnull().sum())

missing values after imputation:
User_ID                    0
Age                        0
Gender                     0
Occupation                 0
Country                    0
Mental_Health_Condition    0
Severity                   0
Consultation_History       0
Stress_Level               0
Sleep_Hours                0
Work_Hours                 0
Physical_Activity_Hours    0
dtype: int64

In [18]:
scaler_minmax=MinMaxScaler()
columns_to_normalize =["Age","Work_Hours"]
data[columns_to_normalize]=scaler_minmax.fit_transform(data[columns_to_normalize])

In [19]:
data.head()

   User_ID       Age  ... Work_Hours Physical_Activity_Hours
0        1  0.723404  ...   0.133333                       6
1        2  0.446809  ...   0.600000                       7
2        3  0.553191  ...   0.644444                       1
3        4  0.127660  ...   0.955556                       4
4        5  0.510638  ...   0.400000                       8

[5 rows x 12 columns]